Artyprod/urls.py
from django.contrib import admin

from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from users.views import CustomLoginView, ResetPasswordView

from users.forms import LoginForm
from users import views
urlpatterns = [
     
    path('admin/', admin.site.urls),
 
    
    path('', include('users.urls')),

    path('login/', CustomLoginView.as_view(redirect_authenticated_user=True, template_name='users/login.html',
                                           authentication_form=LoginForm), name='login'),

    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django import views
from django.urls import path
from .views import  addcomment, home, RegisterView
from . import views
urlpatterns = [
    path('', views.index, name='users-home'),
    path('register/', RegisterView.as_view(), name='users-register'),
    path('addservice/', views.addservice, name='addservice'),
    path('service/<int:service_id>/', views.service_detail, name='service_detail'),
    path('addpersonnel/', views.addpersonnel, name='addpersonnel'),
    path('personnel/<int:personnel_id>/', views.personnel_detail, name='personnel_detail'),
    path('addprojet/', views.addprojet, name='addprojet'),
    path('projet/<int:projet_id>/', views.projet_detail, name='projet_detail'),
    path('addcontact/', views.addcontact, name='addcontact'),
    path('contact/<int:contact_id>/', views.contact_detail, name='contact_detail'),
    path('mespersonnels/', views.mespersonnels, name='mespersonnels'),
    path('addcomment/', addcomment, name='addcomment'),

   
]

users/models.py
from datetime import date, timezone
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.db import models


class Personnell(models.Model):
    nom = models.CharField(max_length=255)
    cv = models.FileField(upload_to='cvs/')
    photo = models.ImageField(upload_to='photos/')
    lien_LinkedIn = models.URLField(blank=True)
    def __str__(self):
        return self.nom 

class Projett(models.Model):
    libell = models.CharField(max_length=255)
    description = models.CharField(max_length=1000)
    date_debut = models.DateField(null=True, default=date.today)
    date_fin = models.DateField(null=True, blank=True)
    achevé = models.CharField(max_length=1, default='N', choices=[('N','non'),('O','oui')])
    equipe = models.ForeignKey('Equipe', on_delete=models.CASCADE)
    user_id = models.IntegerField(default=0)  
    created_by_admin = models.BooleanField(default=False)
    def __str__(self):
        return self.libell 
    
class Service(models.Model):
    nom = models.CharField(max_length=100)
    type =models.CharField(max_length=20,default='Charte graphique',choices=[('Charte graphique','Charte graphique'),('Objet 3D','Objet 3D'),('Scénarisation','Scénarisation')])
    description = models.TextField()
    
    def __str__(self):
        return self.nom

class Detail(models.Model):
    projet = models.ForeignKey(Projett, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    fichier = models.FileField(upload_to='uploads/')

    def __str__(self):
        return self.projet.titre + ' - ' + self.service.nom



class Equipe(models.Model):
    personne = models.ManyToManyField('Personnell')
    def __str__(self):
        membres_str = ", ".join(self.personne.values_list('nom', flat=True))
        return f"({membres_str})"
   
    
class Contact(models.Model):
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    email = models.EmailField()
    tel = models.CharField(max_length=20)
    service=models.ForeignKey('Service', on_delete=models.CASCADE)
    message = models.TextField()
    date_envoi = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.prenom} {self.nom} - {self.date_envoi}"
    



class Commentaire(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()

    def __str__(self):
        return f"Comment by {self.user.username}"

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import ModelForm
from .models import Commentaire, Personnell, Projett, Service,Contact



class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=100,required=True,widget=forms.TextInput(attrs={'placeholder': 'First Name','class': 'form-control', }))
    last_name = forms.CharField(max_length=100,required=True,widget=forms.TextInput(attrs={'placeholder': 'Last Name','class': 'form-control',}))
    username = forms.CharField(max_length=100,required=True,widget=forms.TextInput(attrs={'placeholder': 'Username','class': 'form-control',}))
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Email','class': 'form-control', }))
    password1 = forms.CharField(max_length=50,required=True,widget=forms.PasswordInput(attrs={'placeholder': 'Password','class': 'form-control','data-toggle': 'password','id': 'password',}))
    password2 = forms.CharField(max_length=50, required=True,widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password','class': 'form-control','data-toggle': 'password','id': 'password',}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=100,required=True,widget=forms.TextInput(attrs={'placeholder': 'Username','class': 'form-control',}))
    password = forms.CharField(max_length=50,required=True,widget=forms.PasswordInput(attrs={'placeholder': 'Password','class': 'form-control','data-toggle': 'password','id': 'password','name': 'password',}))
    remember_me = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ['username', 'password', 'remember_me']


class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=100,required=True,widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True,widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email']





class ServiceForm(ModelForm):
    class Meta :
        model = Service
        fields = "__all__" 
        
class ProjetForm(ModelForm):
    class Meta :
        model = Projett
        fields = "__all__" 
        
class PersonnelForm(ModelForm):
    class Meta :
        model = Personnell
        fields = "__all__" 
        
class ContactForm(ModelForm):
    class Meta :
        model = Contact
        fields = "__all__" 
        
class CommentaireForm(ModelForm):
    class Meta :
        model = Commentaire
        fields =  ["content"]

users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordChangeView
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.views import View
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.template import loader
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.db.models import Q
from users.models import Detail, Personnell, Projett, Service

from .forms import CommentaireForm, PersonnelForm, ProjetForm, RegisterForm, LoginForm, ServiceForm
from django.shortcuts import render
from .models import Commentaire, Contact, Equipe
from .forms import ContactForm

def home(request):
    return render(request, 'users/home.html')

def mespersonnels(request):
    personnells= Personnell.objects.all()
    context={'personnells':personnells}
    return render( request,'agence/mespersonnels.html ',context )

class RegisterView(View):
    form_class = RegisterForm
    initial = {'key': 'value'}
    template_name = 'users/register.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to='/')

        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            form.save()

            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}')

            return redirect(to='login')

        return render(request, self.template_name, {'form': form})


class CustomLoginView(LoginView):
    form_class = LoginForm

    def form_valid(self, form):
        remember_me = form.cleaned_data.get('remember_me')

        if not remember_me:
            self.request.session.set_expiry(0)

            self.request.session.modified = True

        return super(CustomLoginView, self).form_valid(form)


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    subject_template_name = 'users/password_reset_subject'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('users-home')




@login_required


def addservice(request):
    if request.method == "POST" :
        form = ServiceForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('service_detail', service_id=form.instance.id)
    else :
        form = ServiceForm() #créer formulaire vide
    return render(request,'agence/majService.html',{'form':form})

def addpersonnel(request):
    if request.method == "POST" :
        form = PersonnelForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('personnel_detail', personnel_id=form.instance.id)
    else :
        form = ServiceForm() #créer formulaire vide
    return render(request,'agence/personnel.html',{'form':form})

def addprojet(request):
    if request.method == "POST":
        form = ProjetForm(request.POST)
        if form.is_valid():
            projet = form.save(commit=False)
            projet.user_id = request.user.id  # Set user_id to the current user's ID

            # Set created_by_admin based on the user's role
            if request.user.is_staff:  # Admin user
                projet.created_by_admin = True
            else:  # Regular user
                projet.created_by_admin = False

            projet.save()
            return redirect('projet_detail', projet_id=projet.id)
    else:
        equipe_list = Equipe.objects.all()
        form = ProjetForm()
    
    context = {'form': form, 'equipe_list': equipe_list}
    return render(request, 'agence/projet.html', context)

def addcomment(request):
    if request.method == "POST":
        form = CommentaireForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user =request.user
            comment.save()
            return redirect('addcomment')
    else:
        form = CommentaireForm()

    projetts = Projett.objects.all()
    comments = Commentaire.objects.all()

    context = {'form': form, 'projetts': projetts, 'comments': comments}
    return render(request, 'agence/comment.html', context)

def addcontact(request):
    if request.method == "POST":
        form = ContactForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('contact_detail', contact_id=form.instance.id)
    else:
        service_list = Service.objects.all()
        form = ContactForm()
        context = {'form': form, 'service_list': service_list}
        return render(request, 'agence/contact.html', context)


    
def index(request):
    projetts = Projett.objects.all()
    personnells = Personnell.objects.all()
    contact= Contact.objects.all()
    services = Service.objects.all()
    equipes = Equipe.objects.all()
    comments = Commentaire.objects.all()
    service_list = Service.objects.all()
    context = {'projetts': projetts,'personnells':personnells,'services': services, 'equipes': equipes, 'comments': comments,'service_list':service_list}
    return render(request, 'users/home.html', context)



def c_detail(request, service_id):
    service = get_object_or_404(Service, pk=service_id)
    projets = Projett.objects.filter(detail__service=service)
    context = {'service': service, 'projets': projets}
    return render(request, 'agence/service_detail.html', context)

def equipe(request):
    personnel = Personnell.objects.all()
    context = {'personnel': personnel}
    return render(request, 'agence/equipe.html', context)

def service_detail(request, service_id):
    service = Service.objects.get(id=service_id)
    template = loader.get_template('users/home.html')
    return render(request, 'users/home.html', {'service': service})

def personnel_detail(request, personnel_id):
    personnel = Personnell.objects.get(id=personnel_id)
    template = loader.get_template('agence/personnel_detail.html')
    return render(request, 'agence/personnel_detail.html', {'personnel': personnel})

def contact_detail(request, contact_id):
    contact = Contact.objects.get(id=contact_id)
    template = loader.get_template('agence/contact_detail.html')
    return render(request, 'agence/contact_detail.html', {'contact': contact})


def projet_detail(request, projet_id):
    projet = Projett.objects.get(id=projet_id)
    template = loader.get_template('agence/projet_detail.html')
    return render(request, 'agence/projet_detail.html', {'projet': projet})



def contact_list(request):
    contacts = Contact.objects.all()
    return render(request, 'contact_list.html', {'contacts': contacts})
    

def add_contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.save()
            return redirect('contact_detail', pk=contact.pk)
    else:
        form = ContactForm()
    return render(request, 'add_contact.html', {'form': form})

users/templates/agence/comment.html
{% extends 'users/base.html' %}

{% block content %}
{% load static %}
<style>
  body {
    background-color:#F0F8FF;
  }

  .con {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    background-color: rgba(255, 255, 255, 0.13);
  }

  .inner-con {
    width: 500px;
    padding: 50px 35px;
    border-radius: 10px;
    background-color: #f9f9f9;
    box-shadow: 0 0 40px rgba(255, 196, 81, 0.6);
  }

  .con h1 {
    font-size: 28px;
    margin-bottom: 15px;
    color: #ffc451;
  }

  .con p {
    margin-bottom: 10px;
    color: #000;
  }

  .con strong {
    font-weight: bold;
    color: #ffc451;
  }
  #comments-container {
    margin-top: 20px;
}

/* Style for the comment form */
.comment-form {
    margin-bottom: 20px;
}

.comment-form textarea {
    width: 100%;
    height: 100px;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
    resize: vertical;
}

.comment-form input[type="submit"] {
    background-color: #4267b2;
    color: #fff;
    border: none;
    padding: 8px 16px;
    border-radius: 4px;
    cursor: pointer;
}

.comment-form input[type="submit"]:hover {
    background-color: #3b5998;
}

/* Style for the comment display section */
#comments-container {
    margin-top: 20px;
}

.comment {
    background-color: #f0f2f5;
    padding: 10px;
    border-radius: 4px;
    margin-bottom: 10px;
}

.comment p {
    margin-bottom: 5px;
}

.comment p:last-child {
    font-size: 12px;
    color: #808080;
}

.comment p:last-child:before {
    content: "Posted by: ";
    font-weight: bold;
}

.projett-container {
    display: inline-block;
    margin: 0 auto;
    max-width: 800px;
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 10px;
    box-shadow: 0 0 10px #ccc;
    transition: all 0.3s ease;
  }
  
  .projett-container:hover {
    transform: scale(1.02);
    box-shadow: 0 0 20px #ccc;
  }

</style>

<section id="portfolio" class="portfolio">
    <div class="container" data-aos="fade-up">

      <div class="section-title">
        <h2>Project</h2>
        <p>Check our Projects</p>
      </div>
      <div class="sma">
        <a href="{% url 'addprojet' %}">Add Project</a>
        <a href="{% url 'addcomment' %}">Add Project</a>

    </div>
    <br>
    <br>
    {% for projet in projetts %}

        <div class="projett-container">
            <h4>{{ projet.libell }}</h4>
            <p>{{ projet.description }}</p>
            {% if projet.date_debut %}
                <p><strong>Date de début:</strong> {{ projet.date_debut }}</p>
            {% endif %}
            {% if projet.date_fin %}
                <p><strong>Date de fin:</strong> {{ projet.date_fin }}</p>
            {% endif %}
            <p><strong>Personnel:</strong> {{ projet.equipe }}</p>
        </div>

    {% endfor %}
     
      
      

    </div>
  </section><!-- End Portfolio Section -->

<h1>Comments</h1>

<!-- Add comment form -->
<form method="post" action="{% url 'addcomment' %}" class="comment-form">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Post Comment">
</form>

<!-- Display existing comments -->
<div id="comments-container">
    {% for comment in comments %}
        <div class="comment">
            <p>{{ comment.content }}</p>
            <p>Posted by: {{ comment.user.username }}</p>
        </div>
    {% empty %}
        <p>No comments yet.</p>
    {% endfor %}
</div>

{% endblock %}

users/templates/agence/contact_detail.html
{% extends 'users/base.html' %}

{% block content %}
{% load static %}

<style>
  body{
    background: linear-gradient(rgba(2, 2, 2, 0.5), rgba(0, 0, 0, 0.5)), url("{% static 'img/cta-bg.jpg' %}") fixed center center;

  }
  .custom-form {
    /* Add your desired styles here */
    background-color: #f2f2f2;
    padding: 20px;
    border-radius: 5px;
    box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
    /* Add more styles as needed */
  }
  
  .custom-form h1 {
    color: #333;
    font-size: 24px;
    /* Add more styles as needed */
  }
  
  .custom-form p {
    color: #666;
    font-size: 16px;
    /* Add more styles as needed */
  }
 .bb{
  margin-top:100px;
 } 
 .cont {
  padding: 20px;
  border-radius: 5px;
  box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
  backdrop-filter: blur(10px);
  background-color: rgba(255, 255, 255, 0.5); /* Adjust the transparency as needed */
}

 .cont strong {
 color:Black;
 }
 .cont h1{
  color:Black;
  text-align:center;
}
.re{
  border:solid 1px Black;
  padding:8px;
  text-align:center;
  border-radius:10px;
 
}
</style>
<div class="bb">
<main id="main">
  
 
  

  <!-- ======= Clients Section ======= -->
 

  <section id="features" class="features">
    <div class="container" data-aos="fade-up">
  
      <div class="row">
        <div class="image col-lg-6" style='background-image: url("{% static 'img/contact-5.jpg' %}");' data-aos="fade-right"></div>
        <div class="col-lg-6" data-aos="fade-left" data-aos-delay="100">
          <div class="cont">
          <h1>Contact Details:</h1>
                    <p><strong>Name:</strong> {{ contact.nom }} {{ contact.prenom }}</p>
                    <p><strong>Email:</strong> {{ contact.email }}</p>
                    <p><strong>Telephone:</strong> {{ contact.tel }}</p>
                    <p><strong>Message:</strong> {{ contact.message }}</p>
                    <p><strong>Service:</strong> {{ contact.service }}</p>
                   <div class="re"> <p>Thank you for your message. We have received your information and will get back to you shortly.</p>        </div>

        </div>
      </div>

        </div>
      </div>
  
    </div>
  </section><!-- End Features Section -->
  
</div>
</div>


{% endblock %}

users/templates/agence/personnel_detail.html
{% extends 'users/base.html' %}

{% block content %}
<style>
  .container{
    height: 520px;
     width: 400px;
     background-color: rgba(255,255,255,0.13);
     position: absolute;
     transform: translate(-50%,-50%);
     top: 50%;
     left: 50%;
     border-radius: 10px;
     backdrop-filter: blur(10px);
     border: 2px solid rgba(255,255,255,0.1);
     box-shadow: 0 0 40px rgba(8,7,16,0.6);
     padding: 50px 35px;
 }
</style>
<div class="container">
  <h1>{{ personnel.nom }} </h1>
  <h1>{{ personnel.prenom }}</h1>
  <p>Email: {{ personnel.email }}</p>
  <p>Telephone: {{ personnel.telephone }}</p>
</div>

{% endblock %}

users/templates/agence/projet.html
{% extends 'users/base.html' %}
{% block content %}
{% load static %}
<style>
  :root {

    --input-color: #99A3BA;
    --input-border: #CDD9ED;
    --input-background: #fff;
    --input-placeholder: #CBD1DC;

    --input-border-focus: #275EFE;

    --group-color: var(--input-color);
    --group-border: var(--input-border);
    --group-background: #EEF4FF;

    --group-color-focus: #fff;
    --group-border-focus: var(--input-border-focus);
    --group-background-focus: #678EFE;

}

.form-field {
    display: block;
    width: 100%;
    padding: 8px 16px;
    line-height: 25px;
    font-size: 14px;
    font-weight: 500;
    font-family: inherit;
    border-radius: 6px;
    -webkit-appearance: none;
    color: var(--input-color);
    border: 1px solid var(--input-border);
    background: var(--input-background);
    transition: border .3s ease;
    &::placeholder {
        color: var(--input-placeholder);
    }
    &:focus {
        outline: none;
        border-color: var(--input-border-focus);
    }
}

.form-group {
    position: relative;
    display: flex;
    width: 100%;
    & > span,
    .form-field {
        white-space: nowrap;
        display: block;
        &:not(:first-child):not(:last-child) {
            border-radius: 0;
        }
        &:first-child {
            border-radius: 6px 0 0 6px;
        }
        &:last-child {
            border-radius: 0 6px 6px 0;
        }
        &:not(:first-child) {
            margin-left: -1px;
        }
    }
    .form-field {
        position: relative;
        z-index: 1;
        flex: 1 1 auto;
        width: 1%;
        margin-top: 0;
        margin-bottom: 0;
    }
    & > span {
        text-align: center;
        padding: 8px 12px;
        font-size: 14px;
        line-height: 25px;
        color: var(--group-color);
        background: var(--group-background);
        border: 1px solid var(--group-border);
        transition: background .3s ease, border .3s ease, color .3s ease;
    }
    &:focus-within {
        & > span {
            color: var(--group-color-focus);
            background: var(--group-background-focus);
            border-color: var(--group-border-focus);
        }
    }
}

html {
    box-sizing: border-box;
    -webkit-font-smoothing: antialiased;
}

* {
    box-sizing: inherit;
    &:before,
    &:after {
        box-sizing: inherit;
    }
}

// Center
body {
    min-height: 100vh;
    font-family: 'Mukta Malar', Arial;
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    background:url("assets/img/blog/blog-inside-post.jpg");
    .form-group {
        max-width: 360px;
        &:not(:last-child) {
            margin-bottom: 32px;
        }
    }
    
}
body{
  background-color:black;
}
.bb{
  margin-top:120px;
  margin-left:300px;
  margin-right:300px;
  margin-bottom:50px;
 
}
.project-form {
  width: 400px;
  margin: 0 auto;
}

.form-group {
  margin-bottom: 20px;
  display: flex;
  flex-direction: column;
}

label {
  font-weight: bold;
  font-size: 16px;
  color: white;
  margin-bottom: 5px;
}

.input-field {
  width: 100%;
}


input[type="text"],
textarea,
select {
  width: 100%;
  height: 40px;
  padding: 8px;
  border: 1px solid #ccc;
  border-radius: 4px;
}

input[type="text"]:hover,
textarea:hover,
select:hover {
  background-color: #4682B4;
}

input[type="submit"] {
  background-color: #4682B4;
  color: #fff;
  border: none;
  border-radius: 4px;
  padding: 10px 20px;
  cursor: pointer;
}

input[type="submit"]:hover {
  background-color: ##4682B4;
}

.addd h1 {
  text-align: center;
  color:white;
}

.addd h1 span {
  color: #4682B4;
  padding: 5px 10px;
  font-size: 50pxpx;
}

</style>
<div class="bb">
  <div class="addd">
    <h1><span>Add</span> New Project</h1>
  </div>
  <form class="project-form" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_libell">Libell:</label>
        {{ form.libell }}
    </div>
    <div class="form-group">
        <label for="id_description">Description:</label>
        {{ form.description }}
    </div>
    <div class="form-group">
        <label for="id_date_debut">Date de début:</label>
        {{ form.date_debut }}
    </div>
    <div class="form-group">
        <label for="id_date_fin">Date de fin:</label>
        {{ form.date_fin }}
    </div>
    <div class="form-group" >
        <label for="id_acheve">Achevé:</label>
        {{ form.achevé }}
    </div>
    <div class="form-group">
        <label for="id_equipe">Équipe:</label>
        {{ form.equipe }}
    </div>
    <!-- Add hidden input fields to store the user_id and created_by_admin values -->
    <input type="hidden" name="user_id" value="{{ request.user.id }}">
    <input type="hidden" name="created_by_admin" value="{% if request.user.is_staff %}True{% else %}False{% endif %}">
    <input type="submit" value="Add">
</form>


  
</div>
   <!-- ======= Footer ======= -->
   <footer id="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>Tempo</h3>
            <p>
              A108 Adam Street <br>
              New York, NY 535022<br>
              United States <br><br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Join Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>

        </div>
      </div>
    </div>

    <div class="container d-md-flex py-4">

      <div class="me-md-auto text-center text-md-start">
        <div class="copyright">
          &copy; Copyright <strong><span>Tempo</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/tempo-free-onepage-bootstrap-theme/ -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
      <div class="social-links text-center text-md-right pt-3 pt-md-0">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
<a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
<a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
<a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
<a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
    </div>
</footer><!-- End Footer -->
{% endblock %}